apiVersion: apps/v1
kind: Deployment
metadata:
  name: quartercog-frontend
  labels:
    app: quartercog
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quartercog
      type: frontend

  template:
    metadata:
      labels:
        app: quartercog
        type: frontend

    spec:
      serviceAccountName: containership
      containers:
        - name: quartercog-frontend
          image: quartercog/quartercog
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
